#!/bin/bash
echo 'My README file' > README.md
echo -e '#!/bin/bash\necho -e "Hello, World"' > 0-hello_world
chmod u+x 0-hello_world
echo -e '#!/bin/bash\ncat /etc/passwd' > 2-hellofile
chmod u+x 2-hellofile
echo -e '#!/bin/bash\ncat /etc/passwd /etc/hosts' > 3-twofiles
chmod u+x 3-twofiles
echo -e '#!/bin/bash\ntail -n 10 /etc/passwd' > 4-lastlines
chmod u+x 4-lastlines
echo -e '#!/bin/bash\nhead -n 10 /etc/passwd' > 5-firstlines
chmod u+x 5-firstlines
echo -e '#!/bin/bash\nhead -n 3 iacta | tail -n 1' > 6-third_line
chmod u+x 6-third_line
echo -e '#!/bin/bash\nls -la > ls_cwd_content' > 8-cwd_state
chmod u+x 8-cwd_state
echo -e '#!/bin/bash\ntail -n 1 iacta >> iacta' > 9-duplicate_last_line
chmod u+x 9-duplicate_last_line
echo -e '#!/bin/bash\nfind . -type f -name "*.js" -delete' > 10-no_more_js
chmod u+x 10-no_more_js
echo -e '#!/bin/bash\nfind . -type d -not -name . | wc -l' > 11-directories
chmod u+x 11-directories
echo -e '#!/bin/bash\nls -t1 | head -n 10' > 12-newest_files
chmod u+x 12-newest_files
echo -e '#!/bin/bash\nsort | uniq -u' > 13-unique
chmod u+x 13-unique
echo -e '#!/bin/bash\ngrep -i "root" /etc/passwd' > 14-findthatword
chmod u+x 14-findthatword
echo -e '#!/bin/bash\ngrep -c -i "bin" /etc/passwd' > 15-countthatword
chmod u+x 15-countthatword
echo -e '#!/bin/bash\ngrep -i "root" -A 3 /etc/passwd' > 16-whatsnext
chmod u+x 16-whatsnext
echo -e '#!/bin/bash\ngrep -i -v "bin" /etc/passwd' > 17-hidethisword
chmod u+x 17-hidethisword
echo -e '#!/bin/bash\ngrep -i "^[a-z]" /etc/ssh/sshd_config' > 18-letteronly
chmod u+x 18-letteronly
echo -e '#!/bin/bash\ntr "A" "Z" | tr "c" "e"' > 19-AZ
chmod u+x 19-AZ
echo -e '#!/bin/bash\ntr -d "cC"' > 20-hiago
chmod u+x 20-hiago
echo -e '#!/bin/bash\nrev' > 21-reverse
chmod u+x 21-reverse
echo -e '#!/bin/bash\ncut -d : -f 1,6 /etc/passwd | sort' > 22-users_and_homes
chmod u+x 22-users_and_homes
echo -e '#!/bin/bash\n' > 100-empty_casks
chmod u+x 100-empty_casks
echo -e '#!/bin/bash\n' > 101-gifs
chmod u+x 101-gifs
echo -e '#!/bin/bash\n' > 102-acrostic
chmod u+x 102-acrostic
echo -e '#!/bin/bash\n' > 103-the_biggest_fan
chmod u+x 103-the_biggest_fan

