#!/bin/bash
echo 'My README file' > README.md
echo -e '#!/bin/bash\npwd' > 0-current_working_directory
chmod u+x 0-current_working_directory
echo -e '#!/bin/bash\nls' > 1-listit
chmod u+x 1-listit
echo -e '#!/bin/bash\ncd ~' > 2-bring_me_home
chmod u+x 2-bring_me_home
echo -e '#!/bin/bash\nls -l' > 3-listfiles
chmod u+x 3-listfiles
echo -e '#!/bin/bash\nls -la' > 4-listmorefiles
chmod u+x 4-listmorefiles
touch 5-listfilesdigitonly
echo -e '#!/bin/bash\nls -lan' > 5-listfilesdigitonly
chmod u+x 5-listfilesdigitonly
touch 6-firstdirectory
echo -e '#!/bin/bash\nmkdir /tmp/my_first_directory' > 6-firstdirectory
chmod u+x 6-firstdirectory
touch 7-movethatfile
echo -e '#!/bin/bash\nmv /tmp/betty /tmp/my_first_directory' > 7-movethatfile
chmod u+x 7-movethatfile
touch 8-firstdelete
echo -e '#!/bin/bash\nrm /tmp/my_first_directory/betty' > 8-firstdelete
chmod u+x 8-firstdelete
touch 9-firstdirdeletion
echo -e '#!/bin/bash\nrmdir /tmp/my_first_directory' > 9-firstdirdeletion
chmod u+x 9-firstdirdeletion
touch 10-back
echo -e '#!/bin/bash\ncd -' > 10-back
chmod u+x 10-back
touch 11-lists
echo -e '#!/bin/bash\nls -la . .. /boot' > 11-lists
chmod u+x 11-lists
touch 12-file_type
echo -e '#!/bin/bash\nfile /tmp/iamafile' > 12-file_type
chmod u+x 12-file_type
touch 13-symbolic_link
echo -e '#!/bin/bash\nln -s /bin/sh ls' > 13-symbolic_link
chmod u+x 13-symbolic_link
touch 14-copy_html
echo -e '#!/bin/bash\ncp -u *.html ../' > 14-copy_html
chmod u+x 14-copy_html
touch 100-lets_move
echo -e '#!/bin/bash\nmv [[:upper:]]* /tmp/u' > 100-lets_move
chmod u+x 100-lets_move
touch 101-clean_emacs
echo -e '#!/bin/bash\nrm *~' > 101-clean_emacs
chmod u+x 101-clean_emacs
touch 102-tree
echo -e '#!/bin/bash\nmkdir -p welcome/to/school' > 102-tree
chmod u+x 102-tree
touch 103-commas
echo -e '#!/bin/bash\nls -xamp' > 103-commas
chmod u+x 103-commas
touch school.mgc
echo -e '0 string SCHOOL School data\n!:mime School' > school.mgc
chmod u+x school.mgc

